### ISSUE TITLE
Add `--force` flag to ignore checks 

### ISSUE THREAD

**Issue by eopb** [eopb/cargo-override#62]
# Problem

If the [registry specified by the user is wrong](
https://github.com/eopb/cargo-override/blob/04e98d117e52a18ec2f9ca4b8d8063ebbd4516d0/src/lib.rs#L101) or the version of the [patch is incompatible with the projects version requirements](https://github.com/eopb/cargo-override/blob/04e98d117e52a18ec2f9ca4b8d8063ebbd4516d0/src/lib.rs#L65) we fail the patch.

We even suggest that the user use `--force` if they are sure they want to apply the patch despite these checks failing. Despite this suggestion, `--force` is not implemented and therefore, will not work.

# Solution

Add a new flag, `--force` which skips registry and version checks.

**Comment by Lindronics** [comment]
Hey 👋🏻  I wouldn't mind picking this one up.

**Comment by eopb** [comment]
Closed by https://github.com/eopb/cargo-override/pull/127
