### ISSUE TITLE
Escape paths when adding them to toml

### ISSUE THREAD

**Issue by eopb** [eopb/cargo-override#87]
# Problem

This code can panic

https://github.com/eopb/cargo-override/blob/79e6cb25779c085bdb70f53028d6bfd28dc07363/src/toml.rs#L71

**Comment by epage** [comment]
Shouldn't the correct approach be to create the tables natively in `toml_edit`, rather than generating it and then parsing it?

**Comment by eopb** [comment]
Yup, that's the plan. I was just struggling to get the exact formatting that I was after when I first tried this, but I expect it's very much doable
